### PR TITLE
feat: cards added

### PR DESCRIPTION
**Pull request by Manishsharma203**
For preview refer following link:
```https://codesandbox.io/s/card-crux-noirr?file=/index.html```

### CODE REVIEW

**Review by sumitch29 — APPROVED** [review]
while hovering share icon add hover effect cursor: pointer

**Review by harshitpaliwal95 — COMMENTED** [review]
- Add some margin to button

**Comment by Manishsharma203** [comment]
> while hovering share icon add hover effect cursor: pointer

sure

**Comment by Manishsharma203** [comment]
> * Add some margin to button

sure. Will add some utility classes for that

**Pull request merged**
